### ISSUE TITLE
ChessMemoryApp not running

### ISSUE THREAD

**Issue by masbou** [ZelonGames/ChessMemoryApp#1]
Hello,
To run ChessMemoryApp needs the file Courses/courses.txt. Where is it or how can I build it ?
Regards

**Comment by ZelonGames** [comment]
Those files are ignored on git because it's an app for personal use only. Sorry!
________________________________
Från: masbou ***@***.***>
Skickat: den 6 oktober 2023 10:35
Till: ZelonGames/ChessMemoryApp ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [ZelonGames/ChessMemoryApp] ChessMemoryApp not running (Issue #1)


Hello,
To run ChessMemoryApp needs the file Courses/courses.txt. Where is it or how can I build it ?
Regards
